version: '3'

services:
  # web:
  #   build:
  #     context: ./wobbuild
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:2-alpine
    ports: 
      - "9200:9200"
      - "9300:9300"

  poxa:
    image: edgurgel/poxa-automated:latest
    environment:
      - PORT=8080
      - POXA_APP_KEY=app_key
      - POXA_SECRET=secret
      - POXA_APP_ID=releaseminion
    ports:
      - "4567:4567"
      - "8080:8080"
      - "8443:8443"