# - ANXS.postgresql,v1.7.1
- DavidWittman.redis
# - playlist.elasticsearch,master
- kosssi.gitconfig
- deiga.sbt
- groover.maven
- SimpliField.node
- rbicker.dockerhost
- rvm_io.ruby
- williamyeh.oracle-java
- gantsign.maven
- andrewrothstein.scala
- robdyke.ant