- name: Install required base packages
  yum: name={{ item }} state=present
  with_items:
    - "@Development tools"
    - curl
    - epel-release
    - libffi-devel
    - python-devel
    - openssl-devel
    - postgresql-devel
    - zlib-devel
    - python-imaging
    - libtiff-devel
    - libjpeg-devel
    - libzip-devel
    - freetype-devel
    - lcms2-devel
    - libwebp-devel
    - tcl-devel
    - tk-devel
    - libxslt-devel
    - libxml2-devel
  
- name: Install Node and pip epel-release
  yum: name={{ item }} state=present
  with_items:
    - nodejs
    - python-pip
    - ruby-devel

# ruby

- name: use Ruby 1.9.3 (required by slanger)
  command: /bin/bash -lc "rvm use 1.9.3"

- name: Update to new versions
  shell: gem install {{ item }}
  with_items:
    - rack -v 1.4.5 --no-rdoc --no-ri 
    - slanger -v 0.6.0 --no-rdoc --no-ri 
# end slanger

- name: Install the required base pip packages
  pip: name={{item}} state=present
  with_items:
    - appdirs
    - packaging
    - virtualenv
    - pip
    - httpie
    - cryptography
    # - ansible

# - name: make sure the latest npm is installed
#   command: npm install -g npm

# - name: Global npm
#   npm: name={{ item }} global=yes
#   with_items:
#     - bower