---
- hosts: all
  become: true
  vars:
    application_name: wobbuild
    document_root: /vagrant
    www_user: vagrant
    www_group: vagrant
  vars_files:
    # - vars/postgres.yml
    - vars/gitconfig.yml
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart {{ application_name }}
      service: name={{ application_name }} state=restarted
  roles:
    # - ANXS.postgresql
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.1', 'ruby-1.9.3'],
        rvm1_install_flags: '--auto-dotfiles',
        rvm1_install_path: /usr/local/rvm,
        rvm1_user: root 
      }
    - DavidWittman.redis
    - kosssi.gitconfig
    - williamyeh.oracle-java
    - gantsign.maven
    - andrewrothstein.scala
    # - { role: robdyke.ant, become: yes }

  tasks:
    - include: tasks/base.yml
    - include: tasks/nginx.yml
    - include: tasks/application.yml